var Ardublockly = Ardublockly || {};
Ardublockly.LOCALISED_TEXT = {
  translationLanguage: "Français",
  title: "Ardublockly",
  blocks: "Blocs",
  /* Menu */
  open: "Ouvrir",
  save: "Enregistrer",
  deleteAll: "Supprimer Tout",
  settings: "Préférences",
  documentation: "Documentation",
  reportBug: "Rapporter un bug",
  examples: "Exemples",
  /* Settings */
  compilerLocation: "Répertoire du compilateur Arduino",
  compilerLocationDefault: "Répertoire du compilateur Arduino par défaut",
  sketchFolder: "Répertoire des sketches",
  sketchFolderDefault: "Répertoire des sketches par défaut",
  arduinoBoard: "Carte Arduino",
  arduinoBoardDefault: "Carte Arduino inconnue",
  comPort: "Port série",
  comPortDefault: "Port série par défaut",
  defaultIdeButton: "Action du bouton IDE",
  defaultIdeButtonDefault: "Action du bouton IDE par défaut",
  language: "Langue",
  languageDefault: "Langue inconnue",
  sketchName: "Nom de sketch",
  /* Arduino console output */
  arduinoOpMainTitle: "Console Arduino IDE",
  arduinoOpWaiting: "En attente du résultat de l'IDE Arduino...",
  arduinoOpUploadedTitle: "Sketch correctement téléversé",
  arduinoOpVerifiedTitle: "Sketch correctement vérifié",
  arduinoOpOpenedTitle: "Sketch ouvert dans l'IDE Arduino",
  arduinoOpOpenedBody: "Le sketch devrait être chargé dans l'IDE Arduino",
  arduinoOpErrorUpVerTitle: "",
  arduinoOpErrorSketchTitle: "",
  arduinoOpErrorFlagTitle: "",
  arduinoOpErrorFlagPrefTitle: "",
  arduinoOpErrorIdeDirTitle: "",
  arduinoOpErrorIdeDirBody: "",
  arduinoOpErrorIdeOptionTitle: "",
  arduinoOpErrorIdeOptionBody: "",
  arduinoOpErrorIdePortTitle: "",
  arduinoOpErrorIdePortBody: "",
  arduinoOpErrorIdeBoardTitle: "",
  arduinoOpErrorIdeBoardBody: "",
  /* Modals */
  noServerTitle: "Serveur Ardublockly non lancé",
  noServerTitleBody: "<p>Afin que les fonctionnalités d'Ardublockly soient toutes disponibles, le serveur Ardublockly doit être lancé localement sur votre ordinateur.</p>" +
                     "<p>Si vous utilisez une version web, vous ne pourrez pas modifier les préférences ou téléverser le code sur une carte Arduino.</p>" +
                     "<p>Les informations d'installation sont disponible sur le <a href=\"https://github.com/carlosperate/ardublockly\">dépôt Ardublockly</a>.</p>" +
                     "<p>Si Ardublockly est déjà installé, assurez-vous que le serveur est correctement lancé.</p>",
  noServerNoLangBody: "Si le serveur Ardublockly n'est pas lancé, la langue ne pourra pas être changée sur l'interface utilisateur.",
  addBlocksTitle: "Blocs additionnels",
  /* Alerts */
  loadNewBlocksTitle: "Ouvrir un fichier Blocs XML",
  loadNewBlocksBody: "Ouvrir un fichier Blocs XML va remplacer les blocs présents sur l'espace de travail.<br/>" +
                     "Êtes-vous sûr de vouloir continuer ?",
  discardBlocksTitle: "Supprimer blocs ?",
  discardBlocksBody: "Il y a %1 blocs sur l'espace de travail.<br/>" +
                     "Êtes-vous sûr de vouloir les supprimer ?",
  invalidXmlTitle: "Fichier Blocs XML invalide",
  invalidXmlBody: "Le fichier Blocs XML n'a pas pu être correctement ouvert. Vérifiez le code XML et réessayez",
  /* Tooltips */
  uploadingSketch: "Téléversement du sketch vers la carte Arduino...",
  uploadSketch: "Téléverser le sketch vers la carte Arduino",
  verifyingSketch: "Vérification du sketch en cours...",
  verifySketch: "Vérifier le sketch",
  openingSketch: "Ouverture du sketch dans l'IDE Arduino...",
  openSketch: "Ouvrir le sketch dans l'IDE Arduino",
  notImplemented: "Fonctionnalité non implémentée",
  /* Prompts */
  ok: "OK",
  okay: "D'accord",
  cancel: "Annuler",
  return: "Retour",
  /* Cards */
  arduinoSourceCode: "Code source Arduino",
  blocksXml: "Blocs XML",
  /* Toolbox Categories*/
  catLogic: "Logique",
  catLoops: "Boucles",
  catMath: "Math",
  catText: "Texte",
  catVariables: "Variables",
  catFunctions: "Fonctions",
  catInputOutput: "Entrées/Sorties",
  catTime: "Temps",
  catAudio: "Audio",
  catMotors: "Moteurs",
  catComms: "Communications",
};
